### ISSUE TITLE
CUDA runtime detection failure.

### ISSUE THREAD

**Issue by veritas9872** [cresset-template/cresset#216]
```
deploy: # API dependent on compose version.
  resources:
    reservations:
      devices:
        - driver: nvidia
          capabilities: [ gpu ]
```
The code above is not working in some versions of Docker Compose.
Adding the line below fixes the issue.
```
runtime: nvidia
```
